apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-02-11T13:42:05Z"
    labels:
      app: web
    name: web-server
    namespace: default
    resourceVersion: "716"
    uid: b44c220e-1ba5-4d25-b004-2a9830f26692
  spec:
    containers:
    - image: nginx:1.20
      imagePullPolicy: IfNotPresent
      name: web-server
      ports:
      - containerPort: 80
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wk92j
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: devops-lab-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-wk92j
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:42:05Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:42:32Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:42:32Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:42:05Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://66ef8dc22ee3499856be8b754fcb53fe725b67032282c5bc8277615a11d7599c
      image: docker.io/library/nginx:1.20
      imageID: docker.io/library/nginx@sha256:38f8c1d9613f3f42e7969c3b1dd5c3277e635d4576713e6453c6193e66270a6d
      lastState: {}
      name: web-server
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-02-11T13:42:32Z"
    hostIP: 172.18.0.2
    phase: Running
    podIP: 10.244.1.2
    podIPs:
    - ip: 10.244.1.2
    qosClass: BestEffort
    startTime: "2026-02-11T13:42:05Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-02-11T13:45:44Z"
    labels:
      app: web
    name: web-server-2
    namespace: default
    resourceVersion: "1029"
    uid: e4b9b8fd-bb08-4191-a40e-b3978ee43c27
  spec:
    containers:
    - image: nginx:1.20
      imagePullPolicy: IfNotPresent
      name: web-server-2
      ports:
      - containerPort: 80
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-f7ffq
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: devops-lab-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-f7ffq
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:45:44Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:45:46Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:45:46Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:45:44Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://8776c6ff95621a2e5fdbb52acd42cdefdf39f6f809bdc2164b4d88824c327c05
      image: docker.io/library/nginx:1.20
      imageID: docker.io/library/nginx@sha256:38f8c1d9613f3f42e7969c3b1dd5c3277e635d4576713e6453c6193e66270a6d
      lastState: {}
      name: web-server-2
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-02-11T13:45:46Z"
    hostIP: 172.18.0.2
    phase: Running
    podIP: 10.244.1.5
    podIPs:
    - ip: 10.244.1.5
    qosClass: BestEffort
    startTime: "2026-02-11T13:45:44Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-02-11T13:49:07Z"
    labels:
      app: web
      version: v1
    name: web-v1
    namespace: default
    resourceVersion: "1353"
    uid: 84610c36-ccbe-437c-9a1e-6f5fd05e21bd
  spec:
    containers:
    - image: nginx:1.20
      imagePullPolicy: IfNotPresent
      name: web-v1
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-qnwfx
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: devops-lab-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-qnwfx
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:49:07Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:49:09Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:49:09Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:49:07Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://29b927581a06745ef2e8f326c1b35c41a7a47265cc626faf4ec23f0e26c4ba60
      image: docker.io/library/nginx:1.20
      imageID: docker.io/library/nginx@sha256:38f8c1d9613f3f42e7969c3b1dd5c3277e635d4576713e6453c6193e66270a6d
      lastState: {}
      name: web-v1
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-02-11T13:49:08Z"
    hostIP: 172.18.0.2
    phase: Running
    podIP: 10.244.1.8
    podIPs:
    - ip: 10.244.1.8
    qosClass: BestEffort
    startTime: "2026-02-11T13:49:07Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-02-11T13:49:15Z"
    labels:
      app: web
      version: v2
    name: web-v2
    namespace: default
    resourceVersion: "1375"
    uid: e410f55b-79f4-4ad5-b107-94018c5d7af0
  spec:
    containers:
    - image: nginx:1.20
      imagePullPolicy: IfNotPresent
      name: web-v2
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-cm42r
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: devops-lab-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-cm42r
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:49:15Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:49:17Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:49:17Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-02-11T13:49:15Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://dc4b78b40d6eacd16bfe1141c4f3fb6447761149003b458f61465efe0aed8742
      image: docker.io/library/nginx:1.20
      imageID: docker.io/library/nginx@sha256:38f8c1d9613f3f42e7969c3b1dd5c3277e635d4576713e6453c6193e66270a6d
      lastState: {}
      name: web-v2
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-02-11T13:49:16Z"
    hostIP: 172.18.0.2
    phase: Running
    podIP: 10.244.1.9
    podIPs:
    - ip: 10.244.1.9
    qosClass: BestEffort
    startTime: "2026-02-11T13:49:15Z"
kind: List
metadata:
  resourceVersion: ""
